# Generated by Django 4.0.7 on 2022-09-02 23:11

import disasterinfosite.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0002_snugget_firehazardpotential_2020_220619_filter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volcano_kingco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.Volcano_kingco.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Summer_kingco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.Summer_kingco.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='LS_kingco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.LS_kingco.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Flood_kingco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.Flood_kingco.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Fire_kingco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.Fire_kingco.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='EQNisqually_2001_171004',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.EQNisqually_2001_171004.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='EQ_kingco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.EQ_kingco.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.AddField(
            model_name='snugget',
            name='EQNisqually_2001_171004_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.eqnisqually_2001_171004'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='EQ_kingco_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.eq_kingco'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Fire_kingco_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.fire_kingco'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Flood_kingco_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.flood_kingco'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='LS_kingco_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.ls_kingco'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Summer_kingco_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.summer_kingco'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Volcano_kingco_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.volcano_kingco'),
        ),
    ]
