# Generated by Django 4.0.7 on 2022-09-01 21:40

import disasterinfosite.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0002_snugget_firehazardpotential_2020_220619_filter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='seattle_kingco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.seattle_kingco.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='seattle_districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.seattle_districts.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='seattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.seattle.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='poly_mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.poly_mask.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='poly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.poly.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='kingco_water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.kingco_water.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='kingco_roads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.kingco_roads.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='kingco_cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.kingco_cities.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='kingco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.kingco.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.AddField(
            model_name='snugget',
            name='kingco_cities_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.kingco_cities'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='kingco_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.kingco'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='kingco_roads_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.kingco_roads'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='kingco_water_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.kingco_water'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='poly_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.poly'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='poly_mask_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.poly_mask'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='seattle_districts_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.seattle_districts'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='seattle_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.seattle'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='seattle_kingco_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.seattle_kingco'),
        ),
    ]
