# Generated by Django 4.0.8 on 2022-12-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0002_snugget_firehazardpotential_2020_220619_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparednessaction',
            name='link',
        ),
        migrations.RemoveField(
            model_name='preparednessaction',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='preparednessaction',
            name='link_text_cn',
        ),
        migrations.RemoveField(
            model_name='preparednessaction',
            name='link_text_en',
        ),
        migrations.RemoveField(
            model_name='preparednessaction',
            name='link_text_es',
        ),
        migrations.RemoveField(
            model_name='preparednessaction',
            name='link_text_ru',
        ),
        migrations.RemoveField(
            model_name='preparednessaction',
            name='link_text_so',
        ),
        migrations.RemoveField(
            model_name='preparednessaction',
            name='link_text_vi',
        ),
        migrations.CreateModel(
            name='PreparednessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('text_cn', models.TextField(default='', null=True)),
                ('text_en', models.TextField(default='', null=True)),
                ('text_ru', models.TextField(default='', null=True)),
                ('text_so', models.TextField(default='', null=True)),
                ('text_es', models.TextField(default='', null=True)),
                ('text_vi', models.TextField(default='', null=True)),
                ('url', models.URLField(default='')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasterinfosite.preparednessaction')),
            ],
        ),
    ]
