# Generated by Django 4.0.8 on 2023-02-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0003_remove_preparednessaction_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoverviewimage',
            name='link_text_ar',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataoverviewimage',
            name='link_text_ko',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='embedsnugget',
            name='text_ar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='embedsnugget',
            name='text_ko',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='pasteventsphoto',
            name='caption_ar',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pasteventsphoto',
            name='caption_ko',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='preparednessaction',
            name='content_text_ar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='preparednessaction',
            name='content_text_ko',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='preparednessaction',
            name='happy_text_ar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='preparednessaction',
            name='happy_text_ko',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='preparednessaction',
            name='property_text_ar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='preparednessaction',
            name='property_text_ko',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='preparednessaction',
            name='title_ar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='preparednessaction',
            name='title_ko',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='preparednessaction',
            name='useful_text_ar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='preparednessaction',
            name='useful_text_ko',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='preparednesslink',
            name='text_ar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='preparednesslink',
            name='text_ko',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='shapefilegroup',
            name='display_name_ar',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shapefilegroup',
            name='display_name_ko',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shapefilegroup',
            name='note_ar',
            field=models.TextField(blank=True, help_text='A note that appears above all snuggets in this section. Use for data caveats or warnings.', null=True),
        ),
        migrations.AddField(
            model_name='shapefilegroup',
            name='note_ko',
            field=models.TextField(blank=True, help_text='A note that appears above all snuggets in this section. Use for data caveats or warnings.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_ar',
            field=models.TextField(default='Information about your organization goes here.', help_text='Describe the data and the agencies that it came from.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_ko',
            field=models.TextField(default='Information about your organization goes here.', help_text='Describe the data and the agencies that it came from.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='area_name_ar',
            field=models.CharField(default='the affected area', help_text="Describe the entire area that this app covers, e.g. 'Oregon' or 'Missoula County'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='area_name_ko',
            field=models.CharField(default='the affected area', help_text="Describe the entire area that this app covers, e.g. 'Oregon' or 'Missoula County'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intro_text_ar',
            field=models.TextField(default='A natural disaster could strike your area at any time.', help_text='A description of what we are trying to help people prepare for, or the goal of your site.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intro_text_ko',
            field=models.TextField(default='A natural disaster could strike your area at any time.', help_text='A description of what we are trying to help people prepare for, or the goal of your site.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_ar',
            field=models.CharField(default='A disaster preparedness website', help_text='A small, catchy description for this site.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_ko',
            field=models.CharField(default='A disaster preparedness website', help_text='A small, catchy description for this site.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_ar',
            field=models.CharField(default='Your Title Here!', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_title_ko',
            field=models.CharField(default='Your Title Here!', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='who_made_this_ar',
            field=models.TextField(default='Information about the creators and maintainers of this particular site.', help_text='Include information about who you are and how to contact you.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='who_made_this_ko',
            field=models.TextField(default='Information about the creators and maintainers of this particular site.', help_text='Include information about who you are and how to contact you.', null=True),
        ),
        migrations.AddField(
            model_name='slideshowsnugget',
            name='text_ar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='slideshowsnugget',
            name='text_ko',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='snuggetpopout',
            name='alt_text_ar',
            field=models.TextField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='snuggetpopout',
            name='alt_text_ko',
            field=models.TextField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='snuggetpopout',
            name='text_ar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='snuggetpopout',
            name='text_ko',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='snuggetsection',
            name='display_name_ar',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='snuggetsection',
            name='display_name_ko',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='textsnugget',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='textsnugget',
            name='content_ko',
            field=models.TextField(null=True),
        ),
    ]
