# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 02:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0005_auto_20170529_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lsld_steepgradezone',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='lsld_steepgradezone',
            name='lookup_val',
        ),
        migrations.AddField(
            model_name='lsld_steepgradezone',
            name='rast',
            field=django.contrib.gis.db.models.fields.RasterField(default=0, srid=4326),
        ),
    ]
