# Generated by Django 4.2.7 on 2023-11-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0005_dataoverviewimage_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snuggetsection',
            name='display_name',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=100),
        ),
        migrations.AlterField(
            model_name='snuggetsection',
            name='display_name_ar',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snuggetsection',
            name='display_name_cn',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snuggetsection',
            name='display_name_en',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snuggetsection',
            name='display_name_es',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snuggetsection',
            name='display_name_ko',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snuggetsection',
            name='display_name_ru',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snuggetsection',
            name='display_name_so',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snuggetsection',
            name='display_name_vi',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snuggetsection',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
