# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 20:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0005_auto_20170608_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsld_steepgradezone_0x0',
            name='rast',
            field=django.contrib.gis.db.models.fields.RasterField(srid=4326),
        ),
        migrations.AlterField(
            model_name='lsld_steepgradezone_0x1',
            name='rast',
            field=django.contrib.gis.db.models.fields.RasterField(srid=4326),
        ),
        migrations.AlterField(
            model_name='lsld_steepgradezone_1x0',
            name='rast',
            field=django.contrib.gis.db.models.fields.RasterField(srid=4326),
        ),
        migrations.AlterField(
            model_name='lsld_steepgradezone_1x1',
            name='rast',
            field=django.contrib.gis.db.models.fields.RasterField(srid=4326),
        ),
    ]
