# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0006_auto_20170612_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snugget',
            name='LSLD_steepgradezone_0x0_filter',
        ),
        migrations.RemoveField(
            model_name='snugget',
            name='LSLD_steepgradezone_0x1_filter',
        ),
        migrations.RemoveField(
            model_name='snugget',
            name='LSLD_steepgradezone_1x0_filter',
        ),
        migrations.RemoveField(
            model_name='snugget',
            name='LSLD_steepgradezone_1x1_filter',
        ),
    ]
